algoritmo media_aritmética
    variáveis
        n1, n2, n3: inteiro
        media: real
    inicio
        escreva(“Informe o primeiro valor: ”)
        leia(n1)

        escreva(“Informe o segundo valor: ”)
        leia(n2)

        escreva(“Informe o terceiro valor: ”)
        leia(n3)

        media = (n1 + n2 + n3)/3
        
        se (condição) então 
            escreva()
        fim-se
        escreva(“Média: ”, media)
    fimalgoritmo